[package]
name = "powdr-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
tower-lsp = "0.20.0"
tokio = { version = "1.32.0", features = ["full"] }
serde_json = "1.0.107"
lalrpop-util = "0.20.0"
powdr = { git = "https://github.com/gzanitti/powdr", branch = "sourceref_fn"}

[build-dependencies]
lalrpop = "0.20.0"
